### ISSUE TITLE
What's the best way to store the tree state? 

### ISSUE THREAD

**Issue by Suibs** [nhn/tui.tree#60]
## Version
latest

## Development Environment
chrome

## Current Behavior
 I started using the tree for my product on the frontend of my website and wanted to know the best option for storing the tree data/state is. I’ve tried modifying the raw data in place but it doesn’t work it doesn't seem like the most efficient method.  I also tried storing the tree instance in the local storage, which wasn’t useful as well. My best guess is to use the read Ajax feature unless there’s another alternative to be explored?

**Comment by dotaitch** [comment]
@Suibs Thank you for your interest in tui.tree :)

Unfortunately, I cannot recommend the best way to store data because it depends on various factors such as the service you create, the amount of data, and so on. The only thing I can say is trying some ways that you mentioned above to find your own best way. 

I hope you find the best solution.
